"""Scientific-loop contracts and helpers for Resonance."""

from resonance.science.contracts import (
    SCHEMA_VERSION,
    ComplexityBudget,
    Direction,
    Expression,
    FalsificationCondition,
    HypothesisSpec,
    HypothesisType,
    MetricName,
    NegativeControl,
    NearZeroBehavior,
    Origin,
    ParameterBounds,
    TargetTransform,
    canonical_json,
    expression_lag_seconds,
    expression_metrics,
    expression_node_count,
    expression_parameters,
    stable_hash,
)

__all__ = [
    "ComplexityBudget",
    "Direction",
    "Expression",
    "FalsificationCondition",
    "HypothesisSpec",
    "HypothesisType",
    "MetricName",
    "NegativeControl",
    "NearZeroBehavior",
    "Origin",
    "ParameterBounds",
    "SCHEMA_VERSION",
    "TargetTransform",
    "canonical_json",
    "expression_lag_seconds",
    "expression_metrics",
    "expression_node_count",
    "expression_parameters",
    "stable_hash",
]
