"""Scientific-loop contracts and helpers for Resonance."""

from resonance.science.contracts import (
    SCHEMA_VERSION,
    ComplexityBudget,
    Direction,
    Expression,
    FalsificationCondition,
    HypothesisSpec,
    HypothesisType,
    MetricName,
    NegativeControl,
    NearZeroBehavior,
    Origin,
    ParameterBounds,
    TargetTransform,
    canonical_json,
    expression_lag_seconds,
    expression_metrics,
    expression_node_count,
    expression_parameters,
    metric_catalog_id,
    metric_catalog_names,
    stable_hash,
)
from resonance.science.review import (
    DeterministicReview,
    DeterministicReviewError,
    ReviewIssue,
    ReviewRecommendation,
    ReviewSpec,
    assert_hypothesis_valid,
    validate_hypotheses,
    validate_hypothesis,
)

__all__ = [
    "ComplexityBudget",
    "DeterministicReview",
    "DeterministicReviewError",
    "Direction",
    "Expression",
    "FalsificationCondition",
    "HypothesisSpec",
    "HypothesisType",
    "MetricName",
    "NegativeControl",
    "NearZeroBehavior",
    "Origin",
    "ParameterBounds",
    "ReviewIssue",
    "ReviewRecommendation",
    "ReviewSpec",
    "SCHEMA_VERSION",
    "TargetTransform",
    "assert_hypothesis_valid",
    "canonical_json",
    "expression_lag_seconds",
    "expression_metrics",
    "expression_node_count",
    "expression_parameters",
    "metric_catalog_id",
    "metric_catalog_names",
    "stable_hash",
    "validate_hypotheses",
    "validate_hypothesis",
]
